### ISSUE TITLE
Github CI Test Suite job intermittently timeout

### ISSUE THREAD

**Issue by vangork** [pravega/pravega-client-rust#395]
**Problem description**
Github CI Test Suite job intermittently got stuck and timeout happens after 30 mins as we set. When the issue happens, it would pop up with the following call stack every 10 seconds.
```
Aug 05, 2022 10:54:45 AM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1StreamCreated@4a006835
java.lang.NullPointerException: startCall() returned a null listener for method io.pravega.controller.stream.api.grpc.v1.ControllerService/getCurrentSegments
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startWrappedCall(ServerImpl.java:636)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.startCall(ServerImpl.java:612)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.access$1800(ServerImpl.java:402)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1StreamCreated.runInternal(ServerImpl.java:543)
	at io.grpc.internal.ServerImpl$ServerTransportListenerImpl$1StreamCreated.runInContext(ServerImpl.java:518)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Problem location**
https://github.com/pravega/pravega-client-rust/runs/7689747158?check_suite_focus=true

**Suggestions for an improvement**

**Comment by vangork** [comment]
The issue has been narrowed down to `test_multi_reader_multi_segments_tail_read` method of pravega-client-integration-test. After dropping reader2 in handler2, when taking reader2 offline it got stuck and blocked the whole process. 
```
Oct 14 05:12:22.778  INFO pravega_client::event::reader: Reader Reader { name: "r1" } is dropped
Oct 14 05:12:22.780  INFO pravega_client::event::reader: Putting reader Reader { name: "r1" } offline
Oct 14 05:12:22.791  INFO pravega_client::event::reader: Reader Reader { name: "r1" } is marked as offline. Ok(())
Oct 14 05:12:22.792  INFO event reader test{auth=true tls=true}: pravega_client_integration_test::event_reader_tests: handle1 was done
Oct 14 05:12:22.885  INFO pravega_client::event::reader: reader r2 owns 0 slices but none is ready to read
Oct 14 05:12:22.885  INFO pravega_client_integration_test::event_reader_tests: r2 failed to acquire any segments
Oct 14 05:12:22.885  INFO pravega_client_integration_test::event_reader_tests: handle2 loop finished
Oct 14 05:12:22.885  INFO pravega_client::event::reader: Reader Reader { name: "r2" } is dropped
test test::integration_test has been running for over 60 seconds
```

Reproduce Env:
CPU: 2 cores
RAM: 7GB
